### ISSUE TITLE
Error "flag provided but not defined: -header-config-path" when using :latest tag

### ISSUE THREAD

**Issue by llech** [PierreZ/goStatic#44]
I was trying to try out the new headerConfig feature. But when I've created configMap with the file under /config/, there was no effect and no error message. So I've tried to use '-header-config-path' parameter:

```
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - args:
        - -header-config-path
        - /config/headers/headerConfig.json
        image: pierrezemb/gostatic:latest
        imagePullPolicy: IfNotPresent
        name: static-cms
        ports:
        - containerPort: 8043
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /srv/http/cms/api/public
          name: cmsfiles
        - mountPath: /config/headers
          name: headers
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: static-cmsfiles
        name: cmsfiles
      - configMap:
          defaultMode: 420
          name: static-headers
        name: headers

```
where the static-headers configmap is:

```
apiVersion: v1
data:
  headerConfig.json: |-
    {
     "configs": [{"fileExtension":"*","headers":[{"key":"Content-Type","value":"application/json;charset=UTF-8"},{"key":"Cache-Control","value":"public, max-age=0, must-revalidate"}],"path":"*"}]
    }
kind: ConfigMap

```
However, I get the error message:

```
flag provided but not defined: -header-config-path 
Usage of /goStatic: 
  -append-header HeaderName:Value 
    	HTTP response header, specified as HeaderName:Value that should be added to all responses. 
  -context string 
    	The 'context' path on which files are served, e.g. 'doc' will serve the files at 'http://localhost:<port>/doc/' 
  -default-user-basic-auth string 
    	Define the user (default "gopher") 
  -enable-basic-auth 
    	Enable basic auth. By default, password are randomly generated. Use --set-basic-auth to set it. 
  -enable-health 
    	Enable health check endpoint. You can call /health to get a 200 response. Useful for Kubernetes, OpenFaas, etc. 
  -fallback string 
    	Default fallback file. Either absolute for a specific asset (/index.html), or relative to recursively resolve (index.html) 
  -password-length int 
    	Size of the randomized password (default 16) 
  -path string 
    	The path for the static files (default "/srv/http") 
  -port int 
    	The listening port (default 8043) 
  -set-basic-auth string 
    	Define the basic auth. Form must be user:password 

```

The new parameter is not in the list.
Could you please check if the :latest tag in docker-hub contains really the actual version of the code, or if it was overwriten by old version?
